version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      docker: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Logging in to Amazon ECR (optional if you push images)...
      # Add ECR login here if you're pushing images
      - echo Pre-build phase complete

  build:
    commands:
      - echo Building React app...
      - npm run build
      - echo Building Docker containers...
      - docker-compose build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating artifact directory...
      - mkdir -p artifact
      - cp -r build/* artifact/

artifacts:
  files:
    - '**/*'
  base-directory: artifact
  discard-paths: no
