version: '3.8'

services:
  frontend:
    image: fakhrealam7/reblog-frontend
    # Map host port 80 → container’s port 3000 so ALB can route HTTP traffic
    ports:
      - "80:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - blog-network

  backend:
    image: fakhrealam7/reblog-backend
    # Don’t publish a host port—use “expose” so only other containers can reach it
    expose:
      - "5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - blog-network

  redis:
    image: redis:alpine
    # Only expose to the network, no host binding
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
