version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $BACKEND_ECR_URI
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $FRONTEND_ECR_URI

  build:
    commands:
      - echo Build backend image...
      - docker build -t $BACKEND_ECR_URI:$IMAGE_TAG backend/
      - echo Build frontend image...
      - docker build -t $FRONTEND_ECR_URI:$IMAGE_TAG frontend/

  post_build:
    commands:
      - echo Push backend image...
      - docker push $BACKEND_ECR_URI:$IMAGE_TAG
      - echo Push frontend image...
      - docker push $FRONTEND_ECR_URI:$IMAGE_TAG

      - echo "Creating deployment manifest..."
      - |
        cat <<EOF > imagedefinitions.json
        [
          {
            "name": "backend-container",
            "imageUri": "$BACKEND_ECR_URI:$IMAGE_TAG"
          },
          {
            "name": "frontend-container",
            "imageUri": "$FRONTEND_ECR_URI:$IMAGE_TAG"
          }
        ]
        EOF

artifacts:
  files:
    - imagedefinitions.json
